pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the project...'
                dir('app') {
                    sh './gradlew clean build'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                dir('app') {
                    sh './gradlew test'
                }
            }
        }
    }
}
